name: Switzerlanded
favicon: null
layout_spectrum: 0.29184
typography_spectrum: 0.28759
title: Switzerlanded
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ff3618'
    - '#010101'
    - '#eab276'
    - '#424242'
  brandStrength: 0.9998350297100842
  lightness: 0.625
  saturation: 0.6681494743097574
  rhythmicContrast: 0.75
purpose: []
