name: Switzerlanded
favicon: null
layout_spectrum: 0.30180352670140564
typography_spectrum: 0.6300591789186001
title: Switzerlanded
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.9998350297100842
  lightness: 0.1086003603413701
  saturation: 0.6681494743097574
  rhythmicContrast: 0.8903054599650204
purpose: []
